{{- if .Values.telemetry.otlpEndpoint }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-otel-sidecar
  labels: {{- include "app.labels" . | nindent 4 }}
data:
  sidecar.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlp:
        endpoint: {{ include "app.fullname" . }}-otel-collector:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          exporters: [otlp]
{{- end }}
